{% set name = "iso3166" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 280fb86d9908f2cbfcbb5f155ed45dfd963e8e9856d902c41f46f63d64f9f639

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - iso3166

about:
  home: https://github.com/deactivated/python-iso3166
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Standalone ISO 3166-1 country definitions

  description: |
    ISO 3166-1 defines two-letter, three-letter, and three-digit country codes.
    python-iso3166 is a self-contained module that converts between these codes
    and the corresponding country name.
  dev_url: https://github.com/deactivated/python-iso3166

extra:
  recipe-maintainers:
    - johnhany97
